// <auto-generated />
using System;
using Events.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Events.Data.Migrations
{
    [DbContext(typeof(EventsDbContext))]
    [Migration("20251128144248_AddAllSubcategories")]
    partial class AddAllSubcategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Events.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DefaultImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryType")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryType = 1,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(5853),
                            Description = "Musical events and concerts",
                            Name = "Music"
                        },
                        new
                        {
                            Id = 2,
                            CategoryType = 2,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(5862),
                            Description = "Art exhibitions and shows",
                            Name = "Art"
                        },
                        new
                        {
                            Id = 3,
                            CategoryType = 3,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(5864),
                            Description = "Business conferences and networking",
                            Name = "Business"
                        },
                        new
                        {
                            Id = 4,
                            CategoryType = 4,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(5866),
                            Description = "Sports events and competitions",
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 5,
                            CategoryType = 5,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(5867),
                            Description = "Theatre performances and plays",
                            Name = "Theatre"
                        },
                        new
                        {
                            Id = 6,
                            CategoryType = 6,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(5868),
                            Description = "Movie screenings and film festivals",
                            Name = "Cinema"
                        },
                        new
                        {
                            Id = 7,
                            CategoryType = 7,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(5869),
                            Description = "Various festivals and celebrations",
                            Name = "Festivals"
                        },
                        new
                        {
                            Id = 8,
                            CategoryType = 8,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(5871),
                            Description = "Exhibitions and displays",
                            Name = "Exhibitions"
                        },
                        new
                        {
                            Id = 9,
                            CategoryType = 9,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(5872),
                            Description = "Professional conferences and seminars",
                            Name = "Conferences"
                        },
                        new
                        {
                            Id = 10,
                            CategoryType = 10,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(5873),
                            Description = "Educational workshops and training",
                            Name = "Workshops"
                        },
                        new
                        {
                            Id = 11,
                            CategoryType = 11,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(5874),
                            Description = "Events pending categorization",
                            Name = "Undefined"
                        });
                });

            modelBuilder.Entity("Events.Models.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TicketUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Date");

                    b.HasIndex("Status");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Events.Models.Entities.EventTag", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("EventId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("EventTags");
                });

            modelBuilder.Entity("Events.Models.Entities.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EnumValue")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ParentCategory")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CategoryId", "EnumValue")
                        .IsUnique();

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6074),
                            Description = "Rock music events and concerts",
                            EnumValue = 1,
                            Name = "Rock",
                            ParentCategory = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6087),
                            Description = "Jazz performances and sessions",
                            EnumValue = 2,
                            Name = "Jazz",
                            ParentCategory = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6089),
                            Description = "Heavy metal and metal subgenres",
                            EnumValue = 3,
                            Name = "Metal",
                            ParentCategory = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6091),
                            Description = "Pop music events",
                            EnumValue = 4,
                            Name = "Pop",
                            ParentCategory = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6092),
                            Description = "Funk music events",
                            EnumValue = 5,
                            Name = "Funk",
                            ParentCategory = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6135),
                            Description = "Punk music events",
                            EnumValue = 6,
                            Name = "Punk",
                            ParentCategory = 1
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6138),
                            Description = "Opera music events",
                            EnumValue = 7,
                            Name = "Opera",
                            ParentCategory = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6154),
                            Description = "Classical music concerts",
                            EnumValue = 8,
                            Name = "Classical",
                            ParentCategory = 1
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6155),
                            Description = "Electronic music and DJ sets",
                            EnumValue = 9,
                            Name = "Electronic",
                            ParentCategory = 1
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6157),
                            Description = "Folk and traditional music",
                            EnumValue = 10,
                            Name = "Folk",
                            ParentCategory = 1
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6159),
                            Description = "Blues music performances",
                            EnumValue = 11,
                            Name = "Blues",
                            ParentCategory = 1
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6160),
                            Description = "Country music events",
                            EnumValue = 12,
                            Name = "Country",
                            ParentCategory = 1
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6163),
                            Description = "Reggae music events",
                            EnumValue = 13,
                            Name = "Reggae",
                            ParentCategory = 1
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6171),
                            Description = "Hip-hop and rap events",
                            EnumValue = 14,
                            Name = "HipHop",
                            ParentCategory = 1
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6172),
                            Description = "Alternative music events",
                            EnumValue = 15,
                            Name = "Alternative",
                            ParentCategory = 1
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6175),
                            Description = "Other music events",
                            EnumValue = 99,
                            Name = "Other",
                            ParentCategory = 1
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6181),
                            Description = "Painting exhibitions and shows",
                            EnumValue = 1,
                            Name = "Painting",
                            ParentCategory = 2
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6185),
                            Description = "Sculpture exhibitions",
                            EnumValue = 2,
                            Name = "Sculpture",
                            ParentCategory = 2
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6187),
                            Description = "Photography exhibitions",
                            EnumValue = 3,
                            Name = "Photography",
                            ParentCategory = 2
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6188),
                            Description = "Digital art exhibitions",
                            EnumValue = 4,
                            Name = "DigitalArt",
                            ParentCategory = 2
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6189),
                            Description = "Street art and urban art events",
                            EnumValue = 5,
                            Name = "StreetArt",
                            ParentCategory = 2
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6234),
                            Description = "Graffiti art exhibitions",
                            EnumValue = 6,
                            Name = "Graffiti",
                            ParentCategory = 2
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6235),
                            Description = "Illustration exhibitions",
                            EnumValue = 7,
                            Name = "Illustration",
                            ParentCategory = 2
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6236),
                            Description = "Performance art events",
                            EnumValue = 8,
                            Name = "PerformanceArt",
                            ParentCategory = 2
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6237),
                            Description = "Installation art exhibitions",
                            EnumValue = 9,
                            Name = "InstallationArt",
                            ParentCategory = 2
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6238),
                            Description = "Contemporary art exhibitions",
                            EnumValue = 10,
                            Name = "ContemporaryArt",
                            ParentCategory = 2
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6239),
                            Description = "Visual arts events",
                            EnumValue = 11,
                            Name = "VisualArts",
                            ParentCategory = 2
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6240),
                            Description = "Mixed media art exhibitions",
                            EnumValue = 12,
                            Name = "MixedMedia",
                            ParentCategory = 2
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6241),
                            Description = "Conceptual art exhibitions",
                            EnumValue = 13,
                            Name = "ConceptualArt",
                            ParentCategory = 2
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6243),
                            Description = "Other art events",
                            EnumValue = 99,
                            Name = "Other",
                            ParentCategory = 2
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6252),
                            Description = "Business networking events",
                            EnumValue = 1,
                            Name = "NetworkingEvents",
                            ParentCategory = 3
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6255),
                            Description = "Startup events and pitches",
                            EnumValue = 2,
                            Name = "Startups",
                            ParentCategory = 3
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6257),
                            Description = "Entrepreneurship seminars",
                            EnumValue = 3,
                            Name = "Entrepreneurship",
                            ParentCategory = 3
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6259),
                            Description = "Marketing conferences",
                            EnumValue = 4,
                            Name = "Marketing",
                            ParentCategory = 3
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6260),
                            Description = "Sales training and events",
                            EnumValue = 5,
                            Name = "Sales",
                            ParentCategory = 3
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6262),
                            Description = "Leadership development events",
                            EnumValue = 6,
                            Name = "Leadership",
                            ParentCategory = 3
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6263),
                            Description = "Finance and investment events",
                            EnumValue = 7,
                            Name = "Finance",
                            ParentCategory = 3
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6264),
                            Description = "Real estate events",
                            EnumValue = 8,
                            Name = "RealEstate",
                            ParentCategory = 3
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6265),
                            Description = "Investment seminars",
                            EnumValue = 9,
                            Name = "Investment",
                            ParentCategory = 3
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6266),
                            Description = "E-commerce events",
                            EnumValue = 10,
                            Name = "ECommerce",
                            ParentCategory = 3
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6268),
                            Description = "Innovation forums",
                            EnumValue = 11,
                            Name = "Innovation",
                            ParentCategory = 3
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6269),
                            Description = "Technology business events",
                            EnumValue = 12,
                            Name = "Technology",
                            ParentCategory = 3
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6270),
                            Description = "HR and management events",
                            EnumValue = 13,
                            Name = "HRManagement",
                            ParentCategory = 3
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6271),
                            Description = "Business strategy workshops",
                            EnumValue = 14,
                            Name = "BusinessStrategy",
                            ParentCategory = 3
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6272),
                            Description = "Product development events",
                            EnumValue = 15,
                            Name = "ProductDevelopment",
                            ParentCategory = 3
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6273),
                            Description = "Other business events",
                            EnumValue = 99,
                            Name = "Other",
                            ParentCategory = 3
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6279),
                            Description = "Football matches and events",
                            EnumValue = 1,
                            Name = "Football",
                            ParentCategory = 4
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6282),
                            Description = "Basketball games and tournaments",
                            EnumValue = 2,
                            Name = "Basketball",
                            ParentCategory = 4
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6283),
                            Description = "Tennis matches and tournaments",
                            EnumValue = 3,
                            Name = "Tennis",
                            ParentCategory = 4
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6284),
                            Description = "Volleyball games",
                            EnumValue = 4,
                            Name = "Volleyball",
                            ParentCategory = 4
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6286),
                            Description = "Swimming competitions",
                            EnumValue = 5,
                            Name = "Swimming",
                            ParentCategory = 4
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6287),
                            Description = "Track and field events",
                            EnumValue = 6,
                            Name = "Athletics",
                            ParentCategory = 4
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6288),
                            Description = "Boxing events and competitions",
                            EnumValue = 7,
                            Name = "Boxing",
                            ParentCategory = 4
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6296),
                            Description = "Wrestling events and competitions",
                            EnumValue = 8,
                            Name = "Wrestling",
                            ParentCategory = 4
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6299),
                            Description = "Gymnastics events and competitions",
                            EnumValue = 9,
                            Name = "Gymnastics",
                            ParentCategory = 4
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6302),
                            Description = "Cycling events and competitions",
                            EnumValue = 10,
                            Name = "Cycling",
                            ParentCategory = 4
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6305),
                            Description = "Other sports events and competitions",
                            EnumValue = 99,
                            Name = "Other",
                            ParentCategory = 4
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6310),
                            Description = "Drama theatre performances",
                            EnumValue = 1,
                            Name = "Drama",
                            ParentCategory = 5
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6312),
                            Description = "Comedy theatre shows",
                            EnumValue = 2,
                            Name = "Comedy",
                            ParentCategory = 5
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6314),
                            Description = "Musical theatre productions",
                            EnumValue = 3,
                            Name = "MusicalTheatre",
                            ParentCategory = 5
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6315),
                            Description = "Tragedy theatre performances",
                            EnumValue = 4,
                            Name = "Tragedy",
                            ParentCategory = 5
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6316),
                            Description = "Experimental theatre",
                            EnumValue = 5,
                            Name = "ExperimentalTheatre",
                            ParentCategory = 5
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6317),
                            Description = "Puppet theatre shows",
                            EnumValue = 6,
                            Name = "PuppetTheatre",
                            ParentCategory = 5
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6319),
                            Description = "Improvisation theatre",
                            EnumValue = 7,
                            Name = "Improvisation",
                            ParentCategory = 5
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6320),
                            Description = "Street theatre performances",
                            EnumValue = 8,
                            Name = "StreetTheatre",
                            ParentCategory = 5
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6322),
                            Description = "Monodrama performances",
                            EnumValue = 9,
                            Name = "Monodrama",
                            ParentCategory = 5
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6324),
                            Description = "Children's theatre shows",
                            EnumValue = 10,
                            Name = "ChildrensTheatre",
                            ParentCategory = 5
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6325),
                            Description = "Other theatre performances",
                            EnumValue = 99,
                            Name = "Other",
                            ParentCategory = 5
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6331),
                            Description = "Feature film screenings",
                            EnumValue = 1,
                            Name = "FeatureFilms",
                            ParentCategory = 6
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6333),
                            Description = "Short film screenings",
                            EnumValue = 2,
                            Name = "ShortFilms",
                            ParentCategory = 6
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6335),
                            Description = "Documentary screenings",
                            EnumValue = 3,
                            Name = "Documentaries",
                            ParentCategory = 6
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6336),
                            Description = "Animation film screenings",
                            EnumValue = 4,
                            Name = "Animation",
                            ParentCategory = 6
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6337),
                            Description = "Independent cinema screenings",
                            EnumValue = 5,
                            Name = "IndependentCinema",
                            ParentCategory = 6
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6338),
                            Description = "Bulgarian cinema screenings",
                            EnumValue = 6,
                            Name = "BulgarianCinema",
                            ParentCategory = 6
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6340),
                            Description = "International cinema screenings",
                            EnumValue = 7,
                            Name = "InternationalCinema",
                            ParentCategory = 6
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6341),
                            Description = "Film premiere events",
                            EnumValue = 8,
                            Name = "FilmPremieres",
                            ParentCategory = 6
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6342),
                            Description = "Student film screenings",
                            EnumValue = 9,
                            Name = "StudentFilms",
                            ParentCategory = 6
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6343),
                            Description = "Film festival events",
                            EnumValue = 10,
                            Name = "FilmFestivals",
                            ParentCategory = 6
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6344),
                            Description = "Other cinema events",
                            EnumValue = 99,
                            Name = "Other",
                            ParentCategory = 6
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6350),
                            Description = "Music festival events",
                            EnumValue = 1,
                            Name = "MusicFestivals",
                            ParentCategory = 7
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6352),
                            Description = "Film festival events",
                            EnumValue = 2,
                            Name = "FilmFestivals",
                            ParentCategory = 7
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6354),
                            Description = "Art festival events",
                            EnumValue = 3,
                            Name = "ArtFestivals",
                            ParentCategory = 7
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6355),
                            Description = "Food and wine festivals",
                            EnumValue = 4,
                            Name = "FoodAndWineFestivals",
                            ParentCategory = 7
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6356),
                            Description = "Cultural festival events",
                            EnumValue = 5,
                            Name = "CulturalFestivals",
                            ParentCategory = 7
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6357),
                            Description = "Folklore festival events",
                            EnumValue = 6,
                            Name = "FolkloreFestivals",
                            ParentCategory = 7
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6358),
                            Description = "Street festival events",
                            EnumValue = 7,
                            Name = "StreetFestivals",
                            ParentCategory = 7
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6360),
                            Description = "Summer festival events",
                            EnumValue = 8,
                            Name = "SummerFestivals",
                            ParentCategory = 7
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6394),
                            Description = "Light festival events",
                            EnumValue = 9,
                            Name = "LightFestivals",
                            ParentCategory = 7
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6396),
                            Description = "Craft beer festivals",
                            EnumValue = 10,
                            Name = "CraftBeerFestivals",
                            ParentCategory = 7
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6397),
                            Description = "Eco festival events",
                            EnumValue = 11,
                            Name = "EcoFestivals",
                            ParentCategory = 7
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6398),
                            Description = "Dance festival events",
                            EnumValue = 12,
                            Name = "DanceFestivals",
                            ParentCategory = 7
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6399),
                            Description = "Tech festival events",
                            EnumValue = 13,
                            Name = "TechFestivals",
                            ParentCategory = 7
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6401),
                            Description = "Other festival events",
                            EnumValue = 99,
                            Name = "Other",
                            ParentCategory = 7
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6409),
                            Description = "Art exhibitions",
                            EnumValue = 1,
                            Name = "ArtExhibitions",
                            ParentCategory = 8
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6412),
                            Description = "Photography exhibitions",
                            EnumValue = 2,
                            Name = "PhotographyExhibitions",
                            ParentCategory = 8
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6413),
                            Description = "Historical exhibitions",
                            EnumValue = 3,
                            Name = "HistoricalExhibitions",
                            ParentCategory = 8
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6414),
                            Description = "Science exhibitions",
                            EnumValue = 4,
                            Name = "ScienceExhibitions",
                            ParentCategory = 8
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6415),
                            Description = "Technology exhibitions",
                            EnumValue = 5,
                            Name = "TechnologyExhibitions",
                            ParentCategory = 8
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6417),
                            Description = "Automotive exhibitions",
                            EnumValue = 6,
                            Name = "AutomotiveExhibitions",
                            ParentCategory = 8
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6418),
                            Description = "Design exhibitions",
                            EnumValue = 7,
                            Name = "DesignExhibitions",
                            ParentCategory = 8
                        },
                        new
                        {
                            Id = 101,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6419),
                            Description = "Cultural heritage exhibitions",
                            EnumValue = 8,
                            Name = "CulturalHeritageExhibitions",
                            ParentCategory = 8
                        },
                        new
                        {
                            Id = 102,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6420),
                            Description = "Educational exhibitions",
                            EnumValue = 9,
                            Name = "EducationalExhibitions",
                            ParentCategory = 8
                        },
                        new
                        {
                            Id = 103,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6421),
                            Description = "Craft exhibitions",
                            EnumValue = 10,
                            Name = "CraftExhibitions",
                            ParentCategory = 8
                        },
                        new
                        {
                            Id = 104,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6422),
                            Description = "Other exhibitions",
                            EnumValue = 99,
                            Name = "Other",
                            ParentCategory = 8
                        },
                        new
                        {
                            Id = 105,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6427),
                            Description = "Technology conferences",
                            EnumValue = 1,
                            Name = "TechConferences",
                            ParentCategory = 9
                        },
                        new
                        {
                            Id = 106,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6430),
                            Description = "Business conferences",
                            EnumValue = 2,
                            Name = "BusinessConferences",
                            ParentCategory = 9
                        },
                        new
                        {
                            Id = 107,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6431),
                            Description = "Startup conferences",
                            EnumValue = 3,
                            Name = "StartupConferences",
                            ParentCategory = 9
                        },
                        new
                        {
                            Id = 108,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6432),
                            Description = "Academic conferences",
                            EnumValue = 4,
                            Name = "AcademicConferences",
                            ParentCategory = 9
                        },
                        new
                        {
                            Id = 109,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6433),
                            Description = "Marketing conferences",
                            EnumValue = 5,
                            Name = "MarketingConferences",
                            ParentCategory = 9
                        },
                        new
                        {
                            Id = 110,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6434),
                            Description = "Science conferences",
                            EnumValue = 6,
                            Name = "ScienceConferences",
                            ParentCategory = 9
                        },
                        new
                        {
                            Id = 111,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6436),
                            Description = "Health and medicine conferences",
                            EnumValue = 7,
                            Name = "HealthAndMedicineConferences",
                            ParentCategory = 9
                        },
                        new
                        {
                            Id = 112,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6437),
                            Description = "AI and innovation conferences",
                            EnumValue = 8,
                            Name = "AIAndInnovationConferences",
                            ParentCategory = 9
                        },
                        new
                        {
                            Id = 113,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6438),
                            Description = "IT security conferences",
                            EnumValue = 9,
                            Name = "ITSecurityConferences",
                            ParentCategory = 9
                        },
                        new
                        {
                            Id = 114,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6439),
                            Description = "Environmental conferences",
                            EnumValue = 10,
                            Name = "EnvironmentalConferences",
                            ParentCategory = 9
                        },
                        new
                        {
                            Id = 115,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6440),
                            Description = "HR conferences",
                            EnumValue = 11,
                            Name = "HRConferences",
                            ParentCategory = 9
                        },
                        new
                        {
                            Id = 116,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6441),
                            Description = "Other conferences",
                            EnumValue = 99,
                            Name = "Other",
                            ParentCategory = 9
                        },
                        new
                        {
                            Id = 117,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6447),
                            Description = "Art workshops",
                            EnumValue = 1,
                            Name = "ArtWorkshops",
                            ParentCategory = 10
                        },
                        new
                        {
                            Id = 118,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6450),
                            Description = "Music workshops",
                            EnumValue = 2,
                            Name = "MusicWorkshops",
                            ParentCategory = 10
                        },
                        new
                        {
                            Id = 119,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6451),
                            Description = "Dance workshops",
                            EnumValue = 3,
                            Name = "DanceWorkshops",
                            ParentCategory = 10
                        },
                        new
                        {
                            Id = 120,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6452),
                            Description = "Photography workshops",
                            EnumValue = 4,
                            Name = "PhotographyWorkshops",
                            ParentCategory = 10
                        },
                        new
                        {
                            Id = 121,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6453),
                            Description = "Cooking workshops",
                            EnumValue = 5,
                            Name = "CookingWorkshops",
                            ParentCategory = 10
                        },
                        new
                        {
                            Id = 122,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6455),
                            Description = "Craft workshops",
                            EnumValue = 6,
                            Name = "CraftWorkshops",
                            ParentCategory = 10
                        },
                        new
                        {
                            Id = 123,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6456),
                            Description = "Startup and entrepreneurship workshops",
                            EnumValue = 7,
                            Name = "StartupAndEntrepreneurshipWorkshops",
                            ParentCategory = 10
                        },
                        new
                        {
                            Id = 124,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6457),
                            Description = "Personal development workshops",
                            EnumValue = 8,
                            Name = "PersonalDevelopmentWorkshops",
                            ParentCategory = 10
                        },
                        new
                        {
                            Id = 125,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6458),
                            Description = "Coding workshops",
                            EnumValue = 9,
                            Name = "CodingWorkshops",
                            ParentCategory = 10
                        },
                        new
                        {
                            Id = 126,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6459),
                            Description = "Language workshops",
                            EnumValue = 10,
                            Name = "LanguageWorkshops",
                            ParentCategory = 10
                        },
                        new
                        {
                            Id = 127,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6460),
                            Description = "Theatre workshops",
                            EnumValue = 11,
                            Name = "TheatreWorkshops",
                            ParentCategory = 10
                        },
                        new
                        {
                            Id = 128,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6461),
                            Description = "Yoga and wellness workshops",
                            EnumValue = 12,
                            Name = "YogaAndWellnessWorkshops",
                            ParentCategory = 10
                        },
                        new
                        {
                            Id = 129,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6462),
                            Description = "Marketing workshops",
                            EnumValue = 13,
                            Name = "MarketingWorkshops",
                            ParentCategory = 10
                        },
                        new
                        {
                            Id = 130,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 42, 47, 943, DateTimeKind.Utc).AddTicks(6465),
                            Description = "Other workshops",
                            EnumValue = 99,
                            Name = "Other",
                            ParentCategory = 10
                        });
                });

            modelBuilder.Entity("Events.Models.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Events.Models.Entities.Event", b =>
                {
                    b.HasOne("Events.Models.Entities.Category", "Category")
                        .WithMany("Events")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Events.Models.Entities.EventTag", b =>
                {
                    b.HasOne("Events.Models.Entities.Event", "Event")
                        .WithMany("EventTags")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Events.Models.Entities.Tag", "Tag")
                        .WithMany("EventTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Events.Models.Entities.SubCategory", b =>
                {
                    b.HasOne("Events.Models.Entities.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Events.Models.Entities.Category", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Events.Models.Entities.Event", b =>
                {
                    b.Navigation("EventTags");
                });

            modelBuilder.Entity("Events.Models.Entities.Tag", b =>
                {
                    b.Navigation("EventTags");
                });
#pragma warning restore 612, 618
        }
    }
}
