name: Build and deploy dotnet core app to Azure Function App - events-prod-ne-func

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SOLUTION_PATH: 'Events'
  FUNCTION_PROJECT_PATH: 'Events/Events.Crawler'
  DOTNET_VERSION: '8.0.x'
  AZURE_FUNCTIONAPP_NAME: 'events-prod-ne-func'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup Node.js (for Playwright)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install System Dependencies for Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3-dev libatk-bridge2.0-dev libdrm2 libxkbcommon0 libgtk-3-0

      - name: 'Restore and Build Solution'
        shell: bash
        run: |
          cd ${{ env.SOLUTION_PATH }}
          if ls *.sln 1> /dev/null 2>&1; then
            echo "Building from solution file..."
            dotnet restore *.sln
            dotnet build *.sln --configuration Release --no-restore
          else
            echo "Building individual projects..."
            # Build in dependency order
            dotnet restore Events.Models/Events.Models.csproj
            dotnet restore Events.Data/Events.Data.csproj
            dotnet restore Events.Services/Events.Services.csproj
            dotnet restore Events.Crawler/Events.Crawler.csproj
            
            dotnet build Events.Models/Events.Models.csproj --configuration Release --no-restore
            dotnet build Events.Data/Events.Data.csproj --configuration Release --no-restore
            dotnet build Events.Services/Events.Services.csproj --configuration Release --no-restore
            dotnet build Events.Crawler/Events.Crawler.csproj --configuration Release --no-restore
          fi

      - name: 'Publish Function App'
        shell: bash
        run: |
          cd ${{ env.FUNCTION_PROJECT_PATH }}
          dotnet publish --configuration Release --output ../../output --no-build

      - name: Install Playwright Browsers
        run: |
          cd output
          npx playwright install chromium --with-deps

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D149CD43094347E294E9C71E8D945430 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FEBB774751BD404CBEB6446EB656CB5B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_99F71B0EA7524611B2C2E462A446E8AC }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          slot-name: 'Production'
          package: './output'